### ISSUE TITLE
Failed to parse  configuration.yaml: Secret greenchoicepass not defined

### ISSUE THREAD

**Issue by machielkreiken** [barisdemirdelen/homeassistant-greenchoice#1]
I'm using the latest homeassistant in a docker running on my Raspberry. I've installed the repo through HACS by adding a custom url for the repo. 

Home Assistant 2022.11.3
Frontend-versie: 20221108.0 - latest

Edited my configuration.yaml with the snippet from the readme.md however i'm still getting an error that my greenchoicepass is not defined.

I've tried reinstalling the integration, removing the directory first, however my HA keeps booting in safemode with this error message.

`
2022-11-20 18:42:32.417 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: Secret greenchoicepass not defined. Activating safe mode`

I have no clue where this is going wrong. Help would be greatly appreciated.

**Comment by muckingaround** [comment]
I just added this custom component to my Home Assistant 2022.11.4 setup without issues.

My first question would be: do you have `greenchoicepass` defined in secrets.yaml? And if you do, have you made sure the spelling is identical?

**Comment by machielkreiken** [comment]
@muckingaround I tried to define it in my configuration.yaml as `greenchoicepass' and tried the actual password in the configuration.yaml, it wasn't clear to me I have to define those in the secrets.yaml. That will probably fix the issue for me! 

@barisdemirdelen perhaps we can add this to the readme.md. For new HA users this would clear things up a lot!

**Comment by muckingaround** [comment]
I hope it fixes your issue.

You should be able to enter it directly but then you should not include the `!secret` part. https://www.home-assistant.io/docs/configuration/secrets/ should help you understand how that works.
