### ISSUE TITLE
Variabele terugleverkosten

### ISSUE THREAD

**Issue by FlexxFR** [barisdemirdelen/homeassistant-greenchoice#10]
Hi, since this month Greenchoice has "Variabele terugleverkosten", can this value retrieved via this integration?
Is it possible to dds this as a new sensor?

**Comment by FlexxFR** [comment]
Not sure how to do this but at least the value of "terugleverkosten" are now available online and via he website.
I assume (hope), this value could now also be retrieved?

![image](https://github.com/user-attachments/assets/30cc0a36-40ce-49c9-ac26-290ba17e3edf)

**Comment by barisdemirdelen** [comment]
Can you tell me what is the Terugleverkosten? How does it relate to Terugleververgoeding? We are currently pulling this info but doing anything with it.

**Comment by FlexxFR** [comment]
Of course, "terugleververgoeding" is the compensation you receive when you deliver more energy (in a year) than you consume.
So, if you produce 3000kwh a year, and only use 2500, you receive for the remaining 500 the "terugleververgoeding". So, for usage in HomeAssistant this value is less useful as you can't predict if and how much you will produce more that you use. (But still nice to have if you want to display all values)

However, since August you always need to pay the new "terugleverkosten" for every kwh you export to the grid. Always, no matter the "saldering", no matter how much you use.

Example:
You produce 3000kwh and use 3000kwh on an annual basis. However in summer you produce more and export to the grid.
For every kwh you export, you earn the current normal tariff (piek/dal), in this case 0,22/0,23. However, you also need to pay the "terugleverkosten" for every kwh. (0,116 currently). So, to calculate your earnings, you need both values and subtract them from each other. Of course, the energy you use directly is still worth the entire tariff value (without any other costs)

To make is very complicated, in the case you produce more than you use, you receive for those kwh's the terugleververgoeding - terugleverkosten (so about 0,03) At least it's not negative :)

Use case:
(Dark green is direct usage, light green is export (so, minus "terugleverkosten"
![image](https://github.com/user-attachments/assets/e6578321-b8e5-41c0-b26c-db320daa5c99)

See the huge difference between july (no terugleverkosten) and august (start of terugleverkosten)
![image](https://github.com/user-attachments/assets/8ef5f7ba-18d5-4708-92f9-0eed4c3b7c86)

Currently I use a static helper for the "terugleverkosten" but I assume these can change as part of the dynamic contract.

**Comment by barisdemirdelen** [comment]
Should be there as a new sensor named electricity_return_cost with #19

**Comment by FlexxFR** [comment]
Value received :)
