### ISSUE TITLE
OIDC inputs removed, not working

### ISSUE THREAD

**Issue by JxxIT** [barisdemirdelen/homeassistant-greenchoice#15]
Hello,

I get an error that says: "custom_components.greenchoice.api.LoginError: Login failed, check your credentials?". 
Debugged a little bit myself, and it seems like the inputs for the OIDC are removed.
I tried logging in by extracting them from the data form the ReturnURL, but no luck.

Any help would be appreciated!

**Comment by barisdemirdelen** [comment]
For me logging in still works, I am no quite sure why this happens for you.

**Comment by JxxIT** [comment]
I am so sorry, I flipped the username and password 😅.
