### ISSUE TITLE
HTTP Error: 500 Server Error: Internal Server Error for url: https://mijn.greenchoice.nl/microbus/request

### ISSUE THREAD

**Issue by pvh0** [barisdemirdelen/homeassistant-greenchoice#4]
Since the 1st of September I'm getting errors in my log:

- HTTP Error: 500 Server Error: Internal Server Error for url: https://mijn.greenchoice.nl/microbus/request
- Error while retrieving meter values!

When brwosing to https://mijn.greenchoice.nl/microbus/request, it gives me a 404 error. Anyone else encountering this issue?

**Comment by barisdemirdelen** [comment]
You are right, I also had issues in my logs, but maybe greenchoice API was problematic during that time? It seems that it is currently working as expected. 

If you browse to that url yourself, you are making a GET request. This not what the API expects, so it is redirecting to the 404 site. API expects a POST request with a valid payload and authentication.
